# Generated by Django 2.2.2 on 2019-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_Base', '0075_remove_error_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcomponent',
            name='sub_components',
            field=models.ManyToManyField(blank=True, related_name='equipment_components_reverse', related_query_name='equipment_component', to='Arimo_IoT_DataAdmin_Base.EquipmentComponent'),
        ),
    ]
