# Generated by Django 2.1.3 on 2018-12-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Arimo_IoT_DataAdmin_Base', '0031_remove_equipmentgeneraltype_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUniqueTypeGroupRiskScoringTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('equipment_unique_type_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_unique_type_group_risk_scoring_task', related_query_name='equipment_unique_type_group_risk_scoring_tasks', to='Arimo_IoT_DataAdmin_Base.EquipmentUniqueTypeGroup')),
            ],
            options={
                'ordering': ('equipment_unique_type_group', '-date'),
            },
        ),
    ]
