# Generated by Django 2.2.3 on 2019-07-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_Base', '0080_equipmentinstance_equipment_unique_type_groups'),
        ('H1stIoT_DataMgmt_Tasks', '0002_equipmentuniquetypegroupcopyriskscorestodbtask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentUniqueTypeGroupCopyRiskScoresToDBTask',
            new_name='EquipmentUniqueTypeGroupDataAggTask',
        ),
    ]
