# Generated by Django 3.2.9 on 2021-11-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_Tasks', '0005_auto_20190726_1837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupriskscoringtask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipmentuniquetypegroupriskscoringtask',
            name='equipment_unique_type_group',
        ),
        migrations.DeleteModel(
            name='EquipmentUniqueTypeGroupDataAggTask',
        ),
        migrations.DeleteModel(
            name='EquipmentUniqueTypeGroupRiskScoringTask',
        ),
    ]
