# Generated by Django 2.2.3 on 2019-07-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_Base', '0080_equipmentinstance_equipment_unique_type_groups'),
        ('Arimo_IoT_DataAdmin_Tasks', '0004_auto_20190726_0526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupdataaggtask',
            unique_together={('equipment_unique_type_group', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupriskscoringtask',
            unique_together={('equipment_unique_type_group', 'date')},
        ),
    ]
