# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_PredMaint', '0014_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
