# Generated by Django 2.1.1 on 2018-11-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_Base', '0028_auto_20181121_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstancedatafielddailyagg',
            options={},
        ),
    ]
