# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_Base', '0002_equipmentuniquetype_equipment_data_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentuniquetype',
            name='equipment_data_fields',
        ),
    ]
