# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_Base', '0002_equipmentuniquetype_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_types', related_query_name='equipment_unique_type', to='Arimo_IoT_DataAdmin_Base.EquipmentDataField'),
        ),
    ]
