# Generated by Django 2.1.1 on 2018-10-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_MaintOps', '0064_auto_20181019_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentproblemperiod',
            name='alerts',
            field=models.ManyToManyField(blank=True, to='H1stIoT_DataMgmt_MaintOps.Alert'),
        ),
        migrations.AlterField(
            model_name='equipmentproblemperiod',
            name='equipment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_diagnoses', related_query_name='equipment_diagnosis', to='H1stIoT_DataMgmt_Base.EquipmentInstance'),
        ),
        migrations.AlterField(
            model_name='equipmentproblemperiod',
            name='equipment_problem_types',
            field=models.ManyToManyField(blank=True, related_name='equipment_diagnoses', related_query_name='equipment_diagnosis', to='H1stIoT_DataMgmt_MaintOps.EquipmentProblemType'),
        ),
    ]
