# Generated by Django 2.1.5 on 2019-02-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_PredMaint', '0085_auto_20190201_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentuniquetypegroupdatafieldpairwisecorrelation',
            options={'ordering': ('equipment_unique_type_group', '-sample_correlation')},
        ),
        migrations.RemoveField(
            model_name='equipmentuniquetypegroupdatafieldpairwisecorrelation',
            name='to_date',
        ),
    ]
