# Generated by Django 2.2.1 on 2019-05-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arimo_IoT_DataAdmin_PredMaint', '0098_auto_20190514_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentproblemperiod',
            old_name='alert_periods',
            new_name='equipment_instance_alert_periods',
        ),
    ]
