# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_MaintOps', '0030_auto_20180722_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='equipment_problem_periods',
            field=models.ManyToManyField(blank=True, related_name='alerts', related_query_name='alert', to='H1stIoT_DataMgmt_MaintOps.EquipmentInstanceProblemDiagnosis'),
        ),
    ]
