# Generated by Django 2.1.4 on 2019-01-06 02:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1stIoT_DataMgmt_MaintOps', '0076_auto_20181220_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='configs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
